# This is a basic workflow to help you get started with Actions

name: Added to Gallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 'pictures/**' 
  pull_request:
    branches: [ main ]
    paths: 'pictures/**' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install exiftool
        run: sudo apt-get install -y exiftool
      
      - name: install graphicsmagick
        run: sudo apt install graphicsmagick
      
      - name: install thumbs-up
        run: npm install -g thumbsup

      # Runs a single command using the runners shell
      - name: generate gallery with thumbsup
        run: thumbsup --input ./pictures --output ./website

      - name: Save gallery to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gallery
          retention-days: 5
          path: website/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: website
